name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:

    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.8
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build web --no-tree-shake-icons

      - name: Create Frontend Directory
        run: mkdir container/build

      - name: Create Frontend Directory
        run: cp -r build/web container/build

      - name: Create backend
        run: cp app.py container

      - name: Create backend
        run: cp requirements.txt container

      - name: Create backend
        run: cp Dockerfile container

      - name: Display Backend Directory Contents
        run: ls -R container

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
            context: ./container
            platforms: linux/arm64v8, linux/amd64
            push: true
            tags: cmulteau/stock_trace:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}